# odometry : wheels or tracks
diameter_wheels: 0.355
distance_between_wheels: 0.672
encoder_config: 1
encoder_dir: 1
angular_dir: -1
back_left_wheel_joint_name: joint_back_left_wheel 
back_right_wheel_joint_name: joint_back_right_wheel 
front_left_wheel_joint_name: joint_front_left_wheel 
front_right_wheel_joint_name: joint_front_right_wheel 
